#!/usr/bin/env rake
# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require File.expand_path('../config/application', __FILE__)

#RubyWebAdminInterface::Application.load_tasks

 task :default => [:make_host_distribution, :copy_akkesb_config] do 
 	puts 'execing rails server'
 	`rails server`
 end

 task :make_host_distribution do
 	puts 'Not configured to make host distribution yet'
 end

 task :copy_akkesb_config do
 	puts 'Not configured to make host distribution yet'
 end